### ISSUE TITLE
Availability of precomputed 200 and 1000-dimensional embeddings?

### ISSUE THREAD

**Issue by dhimmel** [JaesikKim/HiG2Vec#1]
I've enjoyed reading the HiG2Vec manuscript at https://doi.org/10.1093/bioinformatics/btab193. I noticed that the paper states:

> We share both 200- and 1000-dimensional vector representations for human, mouse and yeast species. The implementation is available as well (https://github.com/JaesikKim/HiG2Vec).

I wasn't able to fine the precomputed 200 and 1000-dimensional embeddings. Are these online somewhere? If so, perhaps you could update the README to note their location?

**Comment by JaesikKim** [comment]
Thank you for your interest. You can find the download link in README.org (google drive link).

**Comment by dhimmel** [comment]
Ah my bad. I missed the [Google Drive link](https://drive.google.com/drive/folders/1WIjFSGh9E3z-PIXNOxbwjmG8EJc2j4XT?usp=sharing), which contains files like `hig2vec_human_200dim.pth`. Looking forward to checking them out.

Have you considered depositing these embeddings with Figshare or Zenodo so you can get a citeable DOI for them are ensure longterm preservation?

**Comment by JaesikKim** [comment]
Great! Thanks for the good suggestion. I will look into it later.

**Comment by dhimmel** [comment]
Cool, will close issue now, but please comment if you deposit the datasets somewhere!
