### ISSUE TITLE
Add an open license for the code and data

### ISSUE THREAD

**Issue by dhimmel** [JaesikKim/HiG2Vec#2]
Currently, I don't see any license for the code or data mentioned in the repo. This is problematic for reuse.

I'd suggest the following:

- CC BY 4.0 for GO and GOA data, since that license is used by [GO](http://geneontology.org/docs/go-citation-policy/).
- CC0 for the GO embeddings that are produced by this study (see #1).
- A permissive software license for the code, such as BSD or MIT.

**Comment by JaesikKim** [comment]
Thanks for the good suggestions. I have updated the license in Readme file.

**Comment by dhimmel** [comment]
Thanks! I see the license related commits in this range 78c830300f55f792ca73b428d3bb2f79589c6cd5...af71d1da3cc24d97e2ae4a7b88ec46325365b1ee. Much appreciated.
