### ISSUE TITLE
About graph and batcheddataset

### ISSUE THREAD

**Issue by kch38896** [JaesikKim/HiG2Vec#3]
Hi, Jaesik kim.

I'm trying to use your GO embedding method, but I'm having some problems.

I'm wondering what is meant by "graph" and "BatchedDataset" in sn.py file.
how can I import these modules?

Regards,

**Comment by JaesikKim** [comment]
Hi. Thanks for your interest.

One file was missing. I just uploaded the "graph_dataset.pyx"
(https://github.com/JaesikKim/HiG2Vec/blob/master/hype/graph_dataset.pyx)
Sorry for your inconvenience. 

Once you first setup the code by followings, "graph_dataset.cpp" and "graph_dataset.cpython-39-x86_64-linux-gnu.so" files will be generated in "hype" directory. 
$ git clone https://github.com/JaesikKim/HiG2Vec.git
$ cd HiG2Vec
$ python setup.py build_ext --inplace 

Then, you can run "run_embedding.sh" with no error. (I just tested it in the new environment, and it went well.)

To answer your questions,
1) ["graph" ](https://github.com/JaesikKim/HiG2Vec/blob/a2b51582f6ea6515fcb19280b35a6a5009e948ed/hype/sn.py#L8)
This line means importing ["graph.py"](https://github.com/JaesikKim/HiG2Vec/blob/master/hype/graph.py)
2) ["BatchedDataset"](https://github.com/JaesikKim/HiG2Vec/blob/a2b51582f6ea6515fcb19280b35a6a5009e948ed/hype/sn.py#L9)
This line means importing ["graph_dataset.pyx"](https://github.com/JaesikKim/HiG2Vec/blob/master/hype/graph_dataset.pyx)

FYI, the original implementation code of Poincare embedding is from this link, https://github.com/facebookresearch/poincare-embeddings. 

If you have another issue, please let me know.
Thanks!

**Comment by kch38896** [comment]
Thanks for your reply.
I still get the error again in "run_embdding.sh".

In "embedGene.py", I get error message bellow:
ModuleNotFoundError: No module named 'hype.adjacency_matrix_dataset' 

Please check this issue.
Is this also the same as Poincare embedding code?

**Comment by JaesikKim** [comment]
My apologies.
In "embedGene.py", Please remove one line, then it will work. 
line 10 "from hype.adjacency_matrix_dataset import AdjacencyDataset"

FYI, I've updated this in the repo. Thanks for checking this issue! 🙌

**Comment by kch38896** [comment]
Oh, Thanks a lot.
