### ISSUE TITLE
transitive_closure.py

### ISSUE THREAD

**Issue by nukaemon** [JaesikKim/HiG2Vec#4]
Hello

I've recently read [this paper ](https://www.embopress.org/doi/full/10.15252/embj.2022111071) that utilized HiG2Vec for a certain prediciton task.
I'm interested in generating embeddings with some specific GO subsets of my interest.
One thing I'm not sure so far is 'transitive_closure.py': what does it actually do?
Actually, it seems to contain a syntax error at line 31 where a closing parenthesis is missed.
In addition, I needed to add two lines to make it work as a standalone program.

```
import argparse
import pandas as pd
```

After modifying the script, I executed `python3 data/transitive_closure.py -dset data/example_of_GO.tsv` that finished without an error but didn't generate any new file.

I would like to know the purpose of transitive_closure and its necessity when preparing a new embedding model.

**Comment by JaesikKim** [comment]
Hi nukaemon.
Thanks for the corrections..! The typo might happen when I moved to new university.. Once I checked the code again, there is no typo anymore.

Back to your question, 
In graph theory, transitive closure of a graph is a graph which contains an edge(vertice_i, vertice_j ) whenever
there is a directed path from vertice_i to vertice_j. Therefore, the transitive closure of a directed graph
indicates its reachability relation. (From the supplementary material in my paper)

https://en.wikipedia.org/wiki/Transitive_closure
![image](https://user-images.githubusercontent.com/46479633/202304174-247e025e-6413-4adc-87cb-5e0b60495e35.png)

You can simply check what it works for by the following example.

x = set()
x.add(('1','2','is_a'))
x.add(('2','3', 'is_a'))
transitive_closure(x)

The result is {('1', '2', 'is_a'), ('1', '3', 'is_a'), ('2', '3', 'is_a')}
So 1~3 connection is generated by running transitive closure.py.


So why is the transitive closure step required? So, the method I used in this work is called **Poincare embedding** (from Facebook) (https://arxiv.org/pdf/1705.08039.pdf). And in that paper, they suggested making transitive relations of all relations from the corpus before training, then it learns hierarchical representation in the Poincare space.
So the answer is, necessary if you would like to use Poincare embedding.

Jaesik

**Comment by nukaemon** [comment]
Hello @JaesikKim 

Thank you for your explanation.

I donwloaded the updated transitive_closure.py.
I still needed to put some integer after "nstep=" at line 5, but anyway it now genarated some output files on my GO.tsv.
It actually generated 4 GO_closure_*.tsv files.
If I understand your script correctly, should I use the one with the largest number(i.e. GO_closure_4.tsv in my case) as an input for embedGO.py?

**Comment by JaesikKim** [comment]
Something wrong during updates 😢 .. Just corrected it again!

Yes, correct. the GO_colsure_[highest number].tsv is used for embedGO.py.
FYI, the other files were used in the hierarchy evaluation task in the paper.

**Comment by nukaemon** [comment]
Thank you for the reply.
I will close this issue on transitive_closure.py.

Actually, I'm now in trouble during execution of embedGO.py and probably embedGene.py.
If I can't solve it after some tries, I will post as another issue.

Thank you in advance for your help.
